// autogen entry file to quarkly library
// do not edit this file
export { default as Slider } from './Slider';
export { default as Test } from './Test';
export { default as Audio } from './Audio';
export { default as DisqusComment } from './DisqusComment';
export { default as Disqus } from './Disqus';
export { default as Vimeo } from './Vimeo';
export { default as SoundCloud } from './SoundCloud';
export { default as SvgShape } from './SvgShape';
export { default as YandexMap } from './YandexMap';
export { default as LiveChat } from './LiveChat';
